version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
      tag: '12.14'
    steps:
      - checkout
      - run:
          name: update certificates
          command: |
            sudo apt-get update && sudo apt-get upgrade -y
      - run:
          name: install meteor
          command: |
            curl https://install.meteor.com/ | sh
      - run:
          name: install npm packages
          command: meteor npm i
